name: sh-lint
on:
  - pull_request
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.9
        env:
          SHFMT_OPTS: -i 2
        with:
          sh_checker_comment: false
